export const products = [
  {
    _id: '621235e59540445b3sdfe9s0',
    name: 'Hand Knitted Wool Sweater',
    image: '/images/woolSweater.jpeg',
    description:
      'This beautiful raglan sweater is hand knitted by my mom in Poland. Wool used to make this exclusive garment was obtained by undo another sweater bought in second hand. It is 100% lambswool. ',
    brand: 'none',
    material: 'wool',
    size: 10,
    category: 'Clothes',
    price: 200,
    rating: 5,
    numReviews: 6,
    isHandmade: true,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: '636985e59540445b3c45e6af',
    name: 'Hand Knitted Wool Beanie',
    image: '/images/woolbeanie.jpeg',
    description:
      'This beautiful beanie is hand knitted by me in Poland. Wool used to make this exclusive garment was obtained by undo another sweater bought in second hand. It is 100% lambswool. ',
    brand: 'none',
    material: 'wool',
    category: 'Clothes',
    price: 100,
    rating: 3,
    numReviews: 1,
    isHandmade: true,
    reviews: [],
    stock: 5,
  },
  {
    _id: '6369860d9540445b3c45e6b1',
    name: 'Silk dress',
    image: '/images/silkdress.jpeg',
    description: 'This beautiful dress was found in second hand. It is 100% silk and in perfect shape. ',
    brand: 'Equipment Femme',
    material: 'silk',
    size: 8,
    category: 'Clothes',
    price: 150,
    rating: 0,
    numReviews: 0,
    isHandmade: false,

    reviews: [],
    stock: 1,
  },
  {
    _id: '6369863c9540445b3c45e6b3',
    name: 'Linen dress',
    image: '/images/linendress.jpeg',
    description: 'This beautiful linen dress was found in second hand. It is 100% linen and in perfect shape. ',
    brand: 'Cynthia Rowley',
    material: 'linen',
    size: 8,
    category: 'Clothes',
    price: 80,
    rating: 0,
    numReviews: 0,
    isHandmade: false,

    reviews: [],
    stock: 1,
  },
  {
    _id: '636986579540445b3c45e6b5',
    name: 'Samsung Galaxy S4 Watch',
    image: '/images/s4watch.jpg',
    description:
      "Most of us want to know more about ourselves, so we can be the best version of ourselves. That's why we engineered the all-new Galaxy Watch4 Classic to be the companion to your journey towards a healthier you.",
    brand: 'Amazon',
    category: 'Electronics',
    price: 299.99,
    rating: 4,
    numReviews: 1,
    isNew: false,

    reviews: [],
    stock: 1,
  },
  {
    _id: '636986749540445b3c45e6b7',
    name: 'Samsung Galaxy S21 128GB',
    image: '/images/s22.jpg',
    description:
      'Miss nothing, with Galaxy S21 5G. A camera so good, everyone’s a pro. When capturing your best moments, you no longer have to choose between photo and video. Galaxy S21 captures both, simultaneously, so you’ll never miss a moment. Capture big screen quality videos in stunning 8K resolution* and zoom in with less pixilation with 3x Optical Zoom.',
    brand: 'Amazon',
    category: 'Electronics',
    price: 699.99,
    rating: 0,
    numReviews: 0,
    isNew: false,
    stock: 0,
  },
  {
    _id: '63804a5079636c2ced47757d',
    name: 'Apple Watch SE 40mm',
    image: '/images/apple-watch.jpg',
    brand: 'Apples',
    category: 'Electronics',
    description:
      'Essential features to help you stay connected, active, healthy and safe. Perfect for kids and older adults using Family Setup',
    rating: 0,
    numReviews: 0,
    price: 699.99,
    stock: 5,
    isNew: true,
    reviews: [],
  },
  {
    _id: '6381275e8e8648e00b7c82f7',
    name: 'Shure MV7',
    image: '/images/shure-mv7.jpg',
    brand: 'Shure',
    category: 'Microphones',
    description:
      'Get a professional podcast sound with audio interfaces, hard disk recorders, or direct to computers and mobile devices with the Shure MV7 Podcasting Microphone (Black). This is a professional-quality, broadcast-style dynamic microphone, one that can has both a conventional XLR connection and a USB port. It also supports a 3.5mm headphone output for direct monitoring.',
    rating: 0,
    numReviews: 0,
    price: 449,
    stock: 2,
    isNew: true,
    reviews: [],
  },
  {
    _id: '63895d3b2a3e062504353022',
    name: 'Samsung A73',
    image: '/images/a73.jpg',
    brand: 'Samsung',
    category: 'Electronics',
    description:
      "Blazing 5G. Powerfully connected. It's time to enter into the next chapter. Seriously-fast 5G connection takes your everyday mobile experiences and vastly enhances them with next-level speed. Feel truly connected with seamless streaming, instant sharing and the power to transfer your thoughts to action in a blink.",
    rating: 5,
    numReviews: 1,
    price: 899.99,
    stock: 49,
    isNew: true,
    reviews: [],
  },
];
